# Generated by Django 5.1 on 2024-08-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='user_reg',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user_reg',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user_reg',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='image',
        ),
    ]
