# Generated by Django 4.2.11 on 2024-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
