# Generated by Django 4.2.11 on 2024-08-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0004_alter_user_reg_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
