# Generated by Django 5.1 on 2024-09-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0006_alter_user_reg_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('em', models.EmailField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('passw', models.CharField(max_length=100)),
                ('confirm_pass', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
            ],
        ),
    ]
