# Generated by Django 5.1 on 2024-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0010_feed_user_rename_feedback_feed_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
