# Generated by Django 5.1 on 2024-10-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0017_remove_cart_img_prof_reg_img_user_reg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof_reg',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='img',
        ),
    ]
