# Generated by Django 5.1 on 2024-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0023_alter_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
