# Generated by Django 5.1.2 on 2024-12-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0027_alter_resource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shopid', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='shopimages/')),
                ('category', models.CharField(choices=[('Plants', 'Plants'), ('Tools', 'Tools'), ('Seeds', 'Seeds')], max_length=100)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.prof_reg')),
            ],
        ),
    ]
