# Generated by Django 5.1.3 on 2025-01-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0028_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_reg',
            name='em',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
