# Generated by Django 5.1.3 on 2025-01-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0031_category_reminder_category_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='task_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
