# Generated by Django 5.1.3 on 2025-01-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0033_remove_reminder_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
