# Generated by Django 5.1 on 2025-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0039_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
