# Generated by Django 3.0.5 on 2025-02-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0041_auto_20250226_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.prof_reg'),
        ),
        migrations.AlterField(
            model_name='ptask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.prof_reg'),
        ),
    ]
